M48
; DRILL file {KiCad (6.0.0)} date Mon Jan 24 23:25:11 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-01-24T23:25:11+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.000
%
G90
G05
T1
X35.1Y-56.0
X43.9Y-56.0
X46.1Y-39.0
X46.1Y-73.0
X54.9Y-39.0
X54.9Y-73.0
T0
M30
