M48
; DRILL file {KiCad (6.0.0)} date Mon Feb  7 21:38:08 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-02-07T21:38:08+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C3.000
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T2C6.000
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T3C6.500
%
G90
G05
T2
X70.5Y-97.5
X77.0Y-114.5
X83.5Y-97.5
T3
X71.5Y-55.5
X82.5Y-38.5
X82.5Y-72.5
T1
X69.75Y-28.0G85X72.25Y-28.0
G05
X69.75Y-155.0G85X72.25Y-155.0
G05
T0
M30
