M48
; DRILL file {KiCad (6.0.6)} date Wed Nov 23 18:59:44 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-11-23T18:59:44+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.000
%
G90
G05
T1
X37.6Y-116.05
X46.4Y-116.05
X55.6Y-49.05
X55.6Y-92.05
X64.4Y-49.05
X64.4Y-92.05
T0
M30
