M48
; DRILL file {KiCad (6.0.1)} date Mon Sep 12 17:40:02 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-09-12T17:40:02+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.000
%
G90
G05
T1
X56.6Y-40.55
X56.6Y-63.05
X56.6Y-85.55
X56.6Y-108.05
X65.4Y-40.55
X65.4Y-63.05
X65.4Y-85.55
X65.4Y-108.05
T0
M30
